# Will create Docker images for the webservice version and upload them to Dockerhub
name: Docker build
on:
  workflow_dispatch:
  push:
    branches: [ master, debug-github-ci ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v2
    - uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: hnesk/ocrd_browser:latest
