# Will create Docker images for the webservice version and upload them to Dockerhub
name: Docker build
on:
  workflow_dispatch:
  push:
    branches: [ master, debug-github-ci ]
    tags: ['v*']

jobs:
  tests:
    uses: ./.github/workflows/unittest.yml  # run tests from unittest.yml
  deploy:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    -
      name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: hnesk/ocrd_browser
        tags: type=semver,pattern={{version}}
    - uses: docker/setup-buildx-action@v2
    - uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
